#!/bin/bash

source $(dirname $0)/functions

#
# create connection with the repo
#

header "Opening wallet (90 sec timeout)"

echo Pass ${pass[1]:0:10} ...

vsw setup --ports $HTTP_PORT,$ADMIN_PORT,$WEBHOOK_PORT wallet -k ${pass[1]} user1
r=$?
[[ $r == 0 ]] || fail "opening wallet failed, error $?"

header "Initializing connection"

vsw setup connection || fail "vsw setup connection fails with error $?"

echo PASS
