#!/bin/bash

source $(dirname $0)/functions

#
# create credential definition
#

echo ${pass[1]} | timeout --foreground -k 2 90 vsw setup -n user1 -pn 7060,7061,7062

header "Creating credential definition"

# vsw init -cd || fail -soft "vsw init -cd failed, error $?"

