usage:
	
	@echo "Usage:"
	@echo "	make install-html, generate html in current dir"
	@echo "	make install-local, copy manpages to /usr/local/share/man/man1"

.PHONY: clean install-html install-local

install-html: 
	 @./m2h.sh

install-local:
	@./m2local.sh
