\" This template provides an example of how to generate a Linux man" pages for a new command
\"	NAME Section goes here
\"
.TH VSW-PUBLISH "1" "September 2020" "C. T. Al-Hakim" "Verifiable Software"
.SH NAME  
vsw-publish \- Publish SW package to the VS repo
\"	SYNOPSIS Section goes here
\"
.SH SYNOPSIS  
\fBvsw publish\fR
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]...
\"
\"	DESCRIPTION Section goes here
\"
.SH DESCRIPTION  
\" Add detailed description here
.PP
\fBvsw publish\fR - is used to publish SW packages in the VS software Depo by 
the Developer so it can be intalled by name. All files in the package are
 included.
.br
 By default vsw publish should publish to the public SW Repo
.PP
Mandatory arguments go here...
.TP
\fB\-u\fR, \fB\-\-user [DID|Alias] - Optional\fR 
Holder DID (Decentralized ID)
.TP
\fB\-p\fR, \fB\-\-package\fR [packageName] 
Name of the Package
.TP
\fB\-d\fR, \fB\-\-dir\fR [DirName] 
Name of Directory conataining the Package
.TP
\fB\-h\fR, \fB\-\-help\fR
print help menu
.SS "Exit status:"
.TP
0
if OK,
.TP
1
if minor problems (e.g., cannot access subdirectory),
.TP
2
if serious trouble (e.g., cannot access command\-line argument).

\"
\"	FILES Section goes here
\"
.SH FILES  
.TP  
.I  /etc/vsm_publish.conf  
.TP  
.I  /usr/bin/vsm_publish    
.TP  
.I  .config
\"
\"	EXAMPLES Section goes here
\"
.SH EXAMPLES  
.TP  
\fBvsw publish\~--type\fR\~ edu\fB\~ --issuer\fR\~ issuer_credentials
(Run vsw publish with my_arg2 value for team2 value)      
\"
\"	DIAGNOSTICS Section goes here
\"
.SH DIAGNOSTICS  
.PP
The activity performed using this utility is logged in the file \fB/var/log/vsm_publish\fR      
\"
\"	REPORTING BUGS Section goes here
\"
.SH "REPORTING BUGS"
GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
.br
Report ls translation bugs to <http://translationproject.org/team/>
\"
\"	AUTHOR Section goes here
\"
.SH AUTHOR
Written by Name1 and Name2, ...
\"
\"	COPYRIGHT Section goes here
\"
.SH COPYRIGHT
Copyright \(co 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
\"
\"	CREDITS Section goes here
\"
.SH CREDITS  
.PP	
This man page was created only for demonstration purpose by Chaker Al-Hakim on 09/10/2020
\"
\"	SEE ALSO Section goes here
\"
.SH SEE ALSO  
.br
vsw register(1)  
.br 
vsw list(1)  
.br 
vsw certify(1)  
.br 
vsw publish(1)  
.br 
vsw verify(1)  
.br 
