.TH VSW-REGISTER "1" "September 2020" "C. T. Al-Hakim" "Verifiable Software"
.SH NAME  
vsw register \- Register a developerwith the repo
.SH SYNOPSIS  
\fBvsw register\fR
[\fI\,OPTION\/\fR]... \fI\,username\/\fR
.SH DESCRIPTION  
.PP
\fBvsw register\fR - is used to register a new developer with the repo. This
links the specified username to the developer's DID and optionally associates
other externally identifiable information about the developer.
.PP
The options are as follows:
.TP
.BI "\-\-did " DID
Specify which DID to register. If omitted, the default DID will be used.
.TP
.BI "\-\-domain " domain
Specify a domain name to associate with this user. If this flag is passed,
directions will be provided to prove ownership of the domain.
.TP
.BI "\-\-email " email
Specify an email address to associate with this user. If this flag is passed,
directions will be provided to prove ownership of the email address.
.TP
.BI "\-\-github " github-username
Specify a GitHub username to associate with this user. If this flag is passed,
directions will be provided to prove ownership of the GitHub account.
.TP
\fB\-h\fR, \fB\-\-help\fR
print help menu
.SS "Exit status:"
.TP
0
if registration is successful
.TP
1
if username is in use
.TP
2
if unable to communicate with the repo

.SH EXAMPLES  
.TP  
\fBvsw register\~--email\fR\ user@example.com vswuser1
.SH "REPORTING BUGS"
Open issues at: <https://github.com/verifiablesoftware/vsw/issues>
.SH AUTHOR
Written by C. T. Al-Hakim and B. Dobry
.SH COPYRIGHT
Copyright \(co 2020 Futurewei Technologies, Inc.
.br
License Apache-2.0 License <https://github.com/verifiablesoftware/vsw/blob/master/LICENSE>.
.SH SEE ALSO  
.br 
vsw audit(1)  
.br 
vsw list(1)  
.br 
vsw certify(1)  
.br 
vsw publish(1)  
.br 
vsw verify(1)  
.br 
