\" This template provides an example of how to generate a Linux man" pages for a new command
\"	NAME Section goes here
\"
.TH VSW-VERTIFY "1" "September 2020" "C. T. Al-Hakim" "Verifiable Software"
.SH NAME  
vsw verify \- Verify SW package in the VS repo
\"	SYNOPSIS Section goes here
\"
.SH SYNOPSIS  
\fBvsw verify\fR
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]...
\"
\"	DESCRIPTION Section goes here
\"
.SH DESCRIPTION  
\" Add detailed description here
.PP
\fBvsw verify\fR - vsw verify is used to verify SW packages in the VS software Depo by the Depo Holder
.PP
Mandatory arguments go here...
.TP
\fB\-u\fR, \fB\-\-user [DID]\fR - optional 
Holder DID (Decentralized ID)
.TP
\fB\-p\fR, \fB\-\-package\fR [PackageName] 
Name of Package being verify
.TP
\fB\-f\fR, \fB\-\-file\fR FileName
send output to FileName
.TP
\fB\-h\fR, \fB\-\-help\fR
print help menu
.SS "Exit status:"
.TP
0
if OK,
.TP
1
if minor problems (e.g., cannot access subdirectory),
.TP
2
if serious trouble (e.g., cannot access command\-line argument).

\"
\"	FILES Section goes here
\"
.SH FILES  
.TP  
.I  /etc/vsw verify.conf  
.TP  
.I  /usr/bin/vsw verify    
\"
\"	EXAMPLES Section goes here
\"
.SH EXAMPLES  
.TP  
\fBvsw verify\~--type\fR\~ edu\fB\~ --issuer\fR\~ issuer_credentials
(Run vsw verify with my_arg2 value for team2 value)      
\"
\"	DIAGNOSTICS Section goes here
\"
.SH DIAGNOSTICS  
.PP
The activity performed using this utility is logged in the file \fB/var/log/vsm_verify\fR      
\"
\"	REPORTING BUGS Section goes here
\"
.SH "REPORTING BUGS"
GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
.br
Report ls translation bugs to <http://translationproject.org/team/>
\"
\"	AUTHOR Section goes here
\"
.SH AUTHOR
Written by Name1 and Name2, ...
\"
\"	COPYRIGHT Section goes here
\"
.SH COPYRIGHT
Copyright \(co 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
\"
\"	CREDITS Section goes here
\"
.SH CREDITS  
.PP	
This man page was created only for demonstration purpose by Chaker Al-Hakim on 09/10/2020
\"
\"	SEE ALSO Section goes here
\"
.SH SEE ALSO  
.br
vsw register(1)  
.br 
vsw list(1)  
.br 
vsw certify(1)  
.br 
vsw publish(1)  
.br 
vsw verify(1)  
.br 
