.TH VSW-PUBLISH "1" "September 2020" "C. T. Al-Hakim" "Verifiable Software"
.SH NAME  
vsw-publish \- Publish a software package to the VSW repo
.SH SYNOPSIS  
.B vsw publish
[\fI\,OPTION\/\fR]... [\fI\,path\/\fR]
.SH DESCRIPTION  
.PP
\fBvsw publish\fR - is used to publish software packages to the VSW repo. All
information about the package should be defined in a file called vsw.json. If
.I path
is specified, find vsw.json in that directory, else, look in the current
directory.
.PP
The options are as follows:
.TP
.BI "\-u, \-\-user " DID|alias
Specify the identity with which to publish this package. If omitted, use the
default identity.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help menu.
.SS "Exit status:"
.TP
0
if successful
.TP
1
if conflict is reported by repo
.TP
2
if unable to communicate with the repo
.SH EXAMPLES  
.TP  
\fBvsw publish\~--user\fR\~ user1\f
.SH "REPORTING BUGS"
Open issues at: <https://github.com/verifiablesoftware/vsw/issues>
.SH AUTHOR
Written by C. T. Al-Hakim and B. Dobry
.SH COPYRIGHT
Copyright \(co 2020 Futurewei Technologies, Inc.
.br
License Apache-2.0 License <https://github.com/verifiablesoftware/vsw/blob/master/LICENSE>.
.SH CREDITS  
.PP	
This man page was created only for demonstration purpose by Chaker Al-Hakim on 09/10/2020
.SH SEE ALSO  
.br
vsw register(1)  
.br 
vsw list(1)  
.br 
vsw certify(1)  
.br 
vsw publish(1)  
.br 
vsw verify(1)  
.br 
